export const NICE_CLASSES = [
  { value: 1,  label: "Class 1 — Chemicals & Raw Materials" },
  { value: 2,  label: "Class 2 — Paints, Coatings & Colorants" },
  { value: 3,  label: "Class 3 — Cosmetics & Cleaning Products" },
  { value: 4,  label: "Class 4 — Lubricants & Fuels" },
  { value: 5,  label: "Class 5 — Pharmaceuticals & Veterinary Products" },
  { value: 6,  label: "Class 6 — Metals & Metal Goods" },
  { value: 7,  label: "Class 7 — Machines & Machine Tools" },
  { value: 8,  label: "Class 8 — Hand Tools & Cutlery" },
  { value: 9,  label: "Class 9 — Electronics, Software & Technology" },
  { value: 10, label: "Class 10 — Medical & Surgical Instruments" },
  { value: 11, label: "Class 11 — Lighting, Heating & Cooling Apparatus" },
  { value: 12, label: "Class 12 — Vehicles & Transport Equipment" },
  { value: 13, label: "Class 13 — Firearms & Ammunition" },
  { value: 14, label: "Class 14 — Jewelry, Watches & Precious Metals" },
  { value: 15, label: "Class 15 — Musical Instruments" },
  { value: 16, label: "Class 16 — Paper, Print & Office Materials" },
  { value: 17, label: "Class 17 — Rubber, Plastic & Insulating Materials" },
  { value: 18, label: "Class 18 — Leather Goods & Bags" },
  { value: 19, label: "Class 19 — Non-Metallic Building Materials" },
  { value: 20, label: "Class 20 — Furniture & Household Articles" },
  { value: 21, label: "Class 21 — Kitchenware & Glassware" },
  { value: 22, label: "Class 22 — Ropes, Nets & Fibrous Materials" },
  { value: 23, label: "Class 23 — Yarns & Threads" },
  { value: 24, label: "Class 24 — Textiles & Fabrics" },
  { value: 25, label: "Class 25 — Clothing, Footwear & Headgear" },
  { value: 26, label: "Class 26 — Lace, Ribbons & Fasteners" },
  { value: 27, label: "Class 27 — Floor Coverings & Carpets" },
  { value: 28, label: "Class 28 — Games, Toys & Sporting Goods" },
  { value: 29, label: "Class 29 — Meat, Fish & Processed Foods" },
  { value: 30, label: "Class 30 — Coffee, Tea, Bread & Confectionery" },
  { value: 31, label: "Class 31 — Agricultural & Horticultural Products" },
  { value: 32, label: "Class 32 — Beer, Water & Non-Alcoholic Beverages" },
  { value: 33, label: "Class 33 — Wine, Spirits & Alcoholic Beverages" },
  { value: 34, label: "Class 34 — Tobacco Products & Smokers' Articles" },
  { value: 35, label: "Class 35 — Advertising & Business Services" },
  { value: 36, label: "Class 36 — Insurance & Financial Services" },
  { value: 37, label: "Class 37 — Construction & Repair Services" },
  { value: 38, label: "Class 38 — Telecommunications Services" },
  { value: 39, label: "Class 39 — Transport & Storage Services" },
  { value: 40, label: "Class 40 — Material Treatment Services" },
  { value: 41, label: "Class 41 — Education & Entertainment Services" },
  { value: 42, label: "Class 42 — Scientific, Technical & IT Services" },
  { value: 43, label: "Class 43 — Restaurants & Hospitality" },
  { value: 44, label: "Class 44 — Medical, Beauty & Agricultural Services" },
  { value: 45, label: "Class 45 — Legal & Security Services" },
]
